### PR TITLE
sdcadm#13 Use of xargs with sdc-server lookup is superfluous

### PR DESCRIPTION
**Pull request by bahamat**
should be stricken from documentation.

### CODE REVIEW

**Comment by jclulow** [comment]
I think this also appears in some of the help/usage text in the program itself.

**Comment by bahamat** [comment]
You're right. Let me scrub those as well.

**Comment by bahamat** [comment]
OK, that should do it.

**Comment by jclulow** [comment]
Thanks, Brian.  I'll get this today.

**Comment by bahamat** [comment]
Awesome.

**Comment by trentm** [comment]
merged.  (sorry, @jclulow  I hadn't seen you claim this)

**Pull request merged**
