### PR TITLE
TRITON-2266 cloudapi should be core

### PR DESCRIPTION
**Pull request by bahamat**
Related: joyent/sdc-headnode#58

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Not as confident (in my JS abilities) about leaving a +1 JUST YET, but my offer to test this on Kebecloud applies here too, obviously, and I can look at this more on Monday.

**Comment by bahamat** [comment]
Yeah, sounds good.

To run this in your on DC:

```
# pre check
sdc-sapi /services/$(sdc-sapi /services?name=cloudapi | json uuid) | json -H params.tags
sdc-vmapi /vms/$(sdc-vmname cloudapi) | json -H tags

# install
sdcadm self-update -C experimental --latest
# update
sdcadm experimental update-other

# post-check
sdc-sapi /services/$(sdc-sapi /services?name=cloudapi | json uuid) | json -H params.tags
sdc-vmapi /vms/$(sdc-vmname cloudapi) | json -H tags
```

post-check output should include the `smartdc_type` tag with a value of `core`.

**Comment by bahamat** [comment]
Oh, it’s supposed to be `| json -Ha uuid`. Sorry, that was my fault.

**Review by danmcd — APPROVED** [review]
Ship it.

**Pull request merged**
